# Generated by Django 2.1.2 on 2018-10-25 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Desempeno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='desempeno',
            name='mascotas',
            field=models.ManyToManyField(through='mascotas.Categoria', to='mascotas.Mascota'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='desempeno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.Desempeno'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.Mascota'),
        ),
    ]
